apiVersion: v1
kind: PersistentVolume
metadata:
  name: mobsf-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/filipp/Desktop/mobsf
  claimRef:
    name: mobsf-pvc            # üëà –û–±—Ä–∞—Ç–Ω–∞—è –ø—Ä–∏–≤—è–∑–∫–∞
    namespace: mobsf
    kind: PersistentVolumeClaim
    apiVersion: v1
